version: '3.8'

services:
  backend:
    build: ./baby-adoption-backend
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
    networks:
      - baby-adoption-network

  frontend:
    build: ./baby-adoption-website
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - baby-adoption-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fun
      MYSQL_USER: root
      MYSQL_PASSWORD: 9382019794
      MYSQL_ROOT_PASSWORD: 9382019794
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - baby-adoption-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  baby-adoption-network:
    driver: bridge
